---
  - name: Nginx playbook
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Install Nginx
        apt:
          name: nginx
          state: latest
      - name: Check if nginx is running
        service:
          name: nginx
          state: started
